// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelWizard.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231201055107_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelWizard.Models.DateBooked", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DateBookeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomId = 1,
                            endDate = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startDate = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            RoomId = 2,
                            endDate = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            RoomId = 3,
                            endDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            startDate = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotelWizard.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountDay")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelWizard.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Стандартный люкс с бассеином",
                            IsActive = false,
                            Number = "101",
                            PricePerNight = 100.0m,
                            Type = "I"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Обычный номер",
                            IsActive = false,
                            Number = "201",
                            PricePerNight = 50.0m,
                            Type = "II"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Обычный номер",
                            IsActive = false,
                            Number = "202",
                            PricePerNight = 50.0m,
                            Type = "III"
                        });
                });

            modelBuilder.Entity("HotelWizard.Models.RoomImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            id = 1,
                            RoomId = 1,
                            image = "/images/Rooms/1/1.jpeg"
                        },
                        new
                        {
                            id = 2,
                            RoomId = 1,
                            image = "/images/Rooms/1/2.jpeg"
                        },
                        new
                        {
                            id = 3,
                            RoomId = 1,
                            image = "/images/Rooms/1/3.jpeg"
                        },
                        new
                        {
                            id = 4,
                            RoomId = 1,
                            image = "/images/Rooms/1/4.jpeg"
                        },
                        new
                        {
                            id = 5,
                            RoomId = 2,
                            image = "/images/Rooms/2/1.jpeg"
                        },
                        new
                        {
                            id = 6,
                            RoomId = 2,
                            image = "/images/Rooms/2/2.jpeg"
                        },
                        new
                        {
                            id = 7,
                            RoomId = 2,
                            image = "/images/Rooms/2/3.jpeg"
                        },
                        new
                        {
                            id = 8,
                            RoomId = 2,
                            image = "/images/Rooms/2/4.jpeg"
                        },
                        new
                        {
                            id = 9,
                            RoomId = 3,
                            image = "/images/Rooms/3/1.jpeg"
                        },
                        new
                        {
                            id = 10,
                            RoomId = 3,
                            image = "/images/Rooms/3/2.jpeg"
                        },
                        new
                        {
                            id = 11,
                            RoomId = 3,
                            image = "/images/Rooms/3/3.jpeg"
                        },
                        new
                        {
                            id = 12,
                            RoomId = 3,
                            image = "/images/Rooms/3/4.jpeg"
                        },
                        new
                        {
                            id = 13,
                            RoomId = 3,
                            image = "/images/Rooms/3/5.jpeg"
                        },
                        new
                        {
                            id = 14,
                            RoomId = 3,
                            image = "/images/Rooms/3/6.jpeg"
                        },
                        new
                        {
                            id = 15,
                            RoomId = 3,
                            image = "/images/Rooms/3/7.jpeg"
                        },
                        new
                        {
                            id = 16,
                            RoomId = 3,
                            image = "/images/Rooms/3/8.jpeg"
                        });
                });

            modelBuilder.Entity("HotelWizard.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelWizard.Models.Reservation", b =>
                {
                    b.HasOne("HotelWizard.Models.Users", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelWizard.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelWizard.Models.RoomImage", b =>
                {
                    b.HasOne("HotelWizard.Models.Room", null)
                        .WithMany("ImageArray")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelWizard.Models.Room", b =>
                {
                    b.Navigation("ImageArray");
                });
#pragma warning restore 612, 618
        }
    }
}
